name: GoLint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golint:
    name: GoLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Install Linter
        run: |
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Linter
        run: |
          golint ./...
          staticcheck ./...

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage
          path: coverage.out